package main

import (
	"encoding/json"
	"fmt"
	"html/template"
	"io/ioutil"
	"net/http"
	"strings"
	"syscall/js"
)

func add(this js.Value, i []js.Value) interface{} {
	return i[0].Int() + i[1].Int()
}

func countUp(this js.Value, i []js.Value) interface{} {
	return NeUIUpdate(i[0].String())
}

func registerCallbacks() {
	js.Global().Set("add", js.FuncOf(add))
	js.Global().Set("countUp", js.FuncOf(countUp))
}

func main() {
	c := make(chan struct{}, 0)

	println("WASM Go Initialized")
	// run an http request
	r, _ := http.Get("https://api.chucknorris.io/jokes/random")
	data, _ := ioutil.ReadAll(r.Body)
	println(string(data))

	// register functions
	registerCallbacks()
	<-c
}

var handlers = map[string]func(string) string{
	"ButtonCountercountUp": buttonCounterCountUp,
}

type NewUIUpdateReq struct {
	Method    string `json:"method"`
	Component string `json:"component"`
}

func runHandler(method, component, body string) string {
	handle := handlers[component+method]
	if handle != nil {
		return handle(body)
	}
	return "component method not found"
}

func NeUIUpdate(body string) string {
	var t NewUIUpdateReq
	err := json.Unmarshal([]byte(body), &t)
	if err != nil {
		panic(err)
	}

	return runHandler(t.Method, t.Component, string(body))
}

func buttonCounterCountUp(body string) string {
	var t buttonCounterState
	err := json.Unmarshal([]byte(body), &t)
	if err != nil {
		panic(err)
	}

	t.countUp()
	var s strings.Builder
	template.Must(template.New("ButtonCounter").Parse("Clicked <span id='autoGeneratedID2'>{{.Count}}</span>")).Execute(&s, t)
	return fmt.Sprintf("{\"html\": \"%s\", \"autoGeneratedPropIDForCount\": %d}", filterNewLines(s.String()), t.Count)
}

func filterNewLines(s string) string {
	return strings.Map(func(r rune) rune {
		switch r {
		case 0x000A, 0x000B, 0x000C, 0x000D, 0x0085, 0x2028, 0x2029:
			return -1
		default:
			return r
		}
	}, s)
}

type buttonCounterState struct {
	Count int
}

func (me *buttonCounterState) countUp() {
	me.Count++
}
